# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_zip',
        ),
    ]
